### ISSUE TITLE
Is this guide published somewhere as complied version? like on your blog

### ISSUE THREAD

**Issue by dopcn** [haoNoQ/clang-analyzer-guide#2]
Thanks for sharing

**Comment by haoNoQ** [comment]
Yep, right there in the download section:

https://github.com/haoNoQ/clang-analyzer-guide/releases
https://github.com/haoNoQ/clang-analyzer-guide/releases/download/v0.1/clang-analyzer-guide-v0.1.pdf

README.md mentions it.

**Comment by haoNoQ** [comment]
I'm sorry i'm responding so slowly; i've completely missed the notification about your question, no idea why.

**Comment by haoNoQ** [comment]
I also don't have this posted anywhere else. Myself, at least.
